### ISSUE TITLE
升级出现了问题

### ISSUE THREAD

**Issue by yuano0** [mx-space/core#1012]
操作信息：
操作系统 Ubuntu / 20.04 LTS amd64 (64bit)
面板版本: 3.27.1
系统版本：3.42.4
Linux version 5.4.0-109-generic (buildd@ubuntu) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) mx-space/kami#123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022

问题经过：

有推送【管理中台】新版本，然后去kami文件夹里面执行了一下pnpm i 。

日志信息显示：
``` 
root@yuano:~/mx-space/kami# pnpm i
Scope: all 2 workspace projects
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
packages/kami-design                     |  WARN  deprecated stable@0.1.8
 WARN  GET https://registry.npmjs.org/@esbuild%2Flinux-riscv64 error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@esbuild%2Fandroid-x64 error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@esbuild%2Fdarwin-arm64 error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Packages: +50 -93
++++++++++++++++++++++++++++++++++------------------------------------------------------------------
Progress: resolved 760, reused 705, downloaded 22, added 50, done
node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild: Running postinstall script, done in 91ms

dependencies:
- react-intersection-observer 9.4.2
+ react-intersection-observer 9.4.3
- swr 2.0.3
+ swr 2.1.0

devDependencies:
- @innei/eslint-config-react-ts 0.9.7
+ @innei/eslint-config-react-ts 0.9.8
- @innei/prettier 0.9.7
+ @innei/prettier 0.9.8
- @next/bundle-analyzer 13.1.6
+ @next/bundle-analyzer 13.2.4
- @trivago/prettier-plugin-sort-imports 4.1.0
+ @trivago/prettier-plugin-sort-imports 4.1.1
- @types/node 18.14.1
+ @types/node 18.14.6
- @types/validator 13.7.12
+ @types/validator 13.7.13
- eslint 8.34.0
+ eslint 8.35.0
- zx 7.1.1
+ zx 7.2.0

 WARN  Issues with peer dependencies found
.
├─┬ next 13.1.6
│ └─┬ styled-jsx 5.1.1
│   └── ✕ missing peer @babel/core@"*"
└─┬ react-countup 6.4.1
  └─┬ @rollup/plugin-babel 6.0.3
    └── ✕ missing peer @babel/core@^7.0.0
Peer dependencies that should be installed:
  @babel/core@">=7.0.0 <8.0.0"  

packages/kami-design
├─┬ @floating-ui/react-dom 1.1.0
│ └── ✕ missing peer react-dom@>=16.8.0
├─┬ react-transition-group 4.4.5
│ └── ✕ missing peer react-dom@>=16.6.0
└─┬ rollup-plugin-windicss 1.8.10
  └── ✕ unmet peer rollup@^2.0.0: found 3.18.0
Peer dependencies that should be installed:
  react-dom@>=16.8.0  

The integrity of 1670 files was checked. This might have caused installation to take longer.
Done in 1m 47.1s 
```
问了一下chatGPT 它让我
```
这个错误提示显示安装过程中出现了Git访问权限问题，具体是尝试使用SSH协议从GitHub获取一个依赖库时发生的错误。你可以尝试以下解决方法：

确认你已经配置好了Git和SSH key。如果你还没有生成SSH key，可以参考GitHub官方文档进行配置。

确认你有权限访问这个依赖库。你可以在命令行中使用 ssh -T git@github.com 来测试你的Git访问权限是否正常。

如果你已经配置好了SSH key，并且有访问权限，但是问题仍然存在，那么你可以尝试使用HTTPS协议进行Git操作，例如 https://github.com/Innei/react-smooth-number-counter.git。

如果你的依赖库确实是私有库，你需要确认你的SSH key是否已经添加到你的GitHub账户，并且你的依赖库是否已经添加你的SSH key到其访问列表中。

最后，如果你仍然无法解决问题，你可以尝试在浏览器中打开依赖库的地址，以确认是否存在任何问题。如果是这样，请联系库的维护者以解决问题。
```
根据做了之后，然后还是无法使用pnpm i 进行更新，然后后台也崩了。

![123](https://user-images.githubusercontent.com/106160716/225328938-6d4ffa19-fca6-4ce3-975a-08e4000c0374.png)
![Snipaste_2023-03-15_21-49-24](https://user-images.githubusercontent.com/106160716/225328951-e1d7044b-ad5a-46cc-99ac-4294082fc6ca.png)

请问如何解决呀...裂开了..

**Comment by Innei** [comment]
这个问题不是  pnpm I 导致的。是误删了 core/assets/admin 目录或者应为网络不佳导致的文件丢失。如果升级面板失败可能导致这个问题。我没有做回滚机制。

解决方法： 等 3 秒后进入后台，然后再次升级。
<img width="627" alt="image" src="https://user-images.githubusercontent.com/41265413/225330413-20ee93e7-3273-48ee-aa35-1aa9d9c91f9c.png">

**Comment by yuano0** [comment]
> 这个问题不是 pnpm I 导致的。是误删了 core/assets/admin 目录或者应为网络不佳导致的文件丢失。如果升级面板失败可能导致这个问题。我没有做回滚机制。

![123123](https://user-images.githubusercontent.com/106160716/225332889-a4f01c67-811d-43c8-a2f0-3295647d6a3c.png)
它这个很奇怪，已经显示最高版本了。但是上面还一直在跳，让我继续升级。
![111](https://user-images.githubusercontent.com/106160716/225333096-47e7941f-41ff-4db6-a93e-1c0d1dc79254.png)

**Comment by Innei** [comment]
> > 这个问题不是 pnpm I 导致的。是误删了 core/assets/admin 目录或者应为网络不佳导致的文件丢失。如果升级面板失败可能导致这个问题。我没有做回滚机制。
> 
> ![123123](https://user-images.githubusercontent.com/106160716/225332889-a4f01c67-811d-43c8-a2f0-3295647d6a3c.png) 它这个很奇怪，已经显示最高版本了。但是上面还一直在跳，让我继续升级。 ![111](https://user-images.githubusercontent.com/106160716/225333096-47e7941f-41ff-4db6-a93e-1c0d1dc79254.png)

你直接把 core/assets/admin 删了吧

**Comment by yuano0** [comment]
> 你直接把 core/assets/admin 删了吧

我好像本来就没有这个目录诶....

**Comment by Innei** [comment]
新版本加入了自动下载 dashboard 的功能
