### ISSUE TITLE
预制包本地运行时报错

### ISSUE THREAD

**Issue by GrassBlock1** [mx-space/core#1112]
### Describe the bug

在尝试最新release中的包运行 index.js 时报错，初步分析是因为某个debug文件缺失。

日志：
https://pb.envs.net/?3c853ac794a27ed8#85i9LSkNvLmpbQo5cXJeMXsFp5r7meswHZdT5iAiXE2f

### Reproduction

从release中下载release-linux.zip，解压后运行 `node index.js`

### System Info

```Shell
System:
    OS: Linux 6.4 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 5600U with Radeon Graphics
    Memory: 1.94 GB / 13.51 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 16.20.1 - ~/.local/share/nvm/v16.20.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.4 - ~/.local/share/nvm/v16.20.1/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
`export NODE_ENV=production node ./index.js` 有报错吗

**Comment by GrassBlock1** [comment]
> `export NODE_ENV=production node ./index.js` 有报错吗

有的，报错相同

**Comment by Innei** [comment]
我这好像没问题。

**Comment by ttimochan** [comment]
> > `export NODE_ENV=production node ./index.js` 有报错吗
> 
> 有的，报错相同

请你使用 `hostnamectl` 命令提供一下系统信息，请你使用 `ldd --version` 提供 Glibc 信息，谢谢

**Comment by GrassBlock1** [comment]
> 我这好像没问题。

hmm 我自己打包一个看看吧

**Comment by GrassBlock1** [comment]
用pm2跑倒是可以，不知道是不是环境变量的问题
