### ISSUE TITLE
[BUG] 连接到数据库时产生错误

### ISSUE THREAD

**Issue by GrassBlock1** [mx-space/core#1116]
如题，在尝试部署到 [Zeabur](https://zeabur.com) 时，出现以下报错：
![图片](https://github.com/mx-space/core/assets/46253950/c7979d93-11c0-4641-a2a1-7933c30f168c)

尝试关闭Redis的强制要求密码后，结果如下：
![图片](https://github.com/mx-space/core/assets/46253950/2743f548-b2b9-468d-a43a-be6ba8fc0959)

在本地（Arch Linux with Node.js 16.20.1）运行（连接到其数据库），出现了以下错误：
![图片](https://github.com/mx-space/core/assets/46253950/bf5e634b-64a7-4392-a3bb-fa90e27be5f5)

这是我所使用的脚本，并且已经确保所引用的环境变量均存在且有效：
https://github.com/BlockG-ws/mxspace-z/blob/master/run.sh

使用 zeabur 部署时所使用的 Docker 镜像为 node:16-alpine。

和 zeabur 相关人员讨论后，发现可能涉及的issue：
https://github.com/redis/ioredis/issues/553

**Comment by Innei** [comment]
@GrassBlock1 试试新版有没有解决你的问题

**Comment by GrassBlock1** [comment]
> @GrassBlock1 试试新版有没有解决你的问题

应该吧.....至少Redis不出错了....我再观察观察
![图片](https://github.com/mx-space/core/assets/46253950/5043a97d-95ee-417e-aa46-ecdeb0b892ed)

**Comment by GrassBlock1** [comment]
已解决
