### ISSUE TITLE
一些功能/外观改进建议

### ISSUE THREAD

**Issue by zhuozhiyongde** [mx-space/core#1135]
### Clear and concise description of the problem

如题，具体如下：

* 后台菜单栏子选项颜色灰一点区分度灰更高？且各个标题栏中可以增加一些 margin？

  ![image](https://github.com/Innei/Shiro/assets/36695271/19f3d3b4-3e70-4d9f-b704-85eaa3839d23)

* 后台的网站 icon 希望能根据环境切换黑暗模式：

  ![Cleanshot-2023-09-10-at-19 55 30](https://github.com/Innei/Shiro/assets/36695271/bc10ea4a-f91b-4764-bf65-b84793132941)

* 后台有新版本的时候的升级提示无法永久关闭（甚至不关闭的话会堆叠)

  ![image](https://github.com/Innei/Shiro/assets/36695271/e2595f22-e181-4d7c-a38f-b3fc644ff3d8)

### Suggested solution

对于后台提示，增加duration参数，增加永久关闭选项。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
`mx-admin` 不计划维护了
