### ISSUE TITLE
部署后端后前端无法验证主人身份

### ISSUE THREAD

**Issue by BLxcwg666** [mx-space/core#1137]
### Describe the bug

如题，我按照[这篇文章](https://blog.xcnya.cn/archives/68.html)的方法通过 Docker 搭建了后端，随后我无论是在本地还是在 Vercel 上搭建前端（Kami 和 Shiro 都试过），前端无法验证我是主人的身份

![image](https://github.com/mx-space/core/assets/66854530/5a942988-9c4e-48c3-aa7f-2c709ee31e23)

我通过 DevTools 查看 Cookies，发现前端和后端都是存在 `mx-token` 这个 Cookie 的，并且值一模一样

![image](https://github.com/mx-space/core/assets/66854530/a971bcb9-65b3-4733-81a4-30c330bd6497)
![image](https://github.com/mx-space/core/assets/66854530/ab11c616-e256-4244-8398-4256d9b0eb7b)

我分别在 3 台服务器上重试过，但无论是使用 Docker 还是手动部署，都存在该问题
我认为这是一个 Bug，如果不是，我想求助是我在部署的过程中疏漏了哪一步吗
谢谢！

### Reproduction

没看懂这一项

### System Info

Server 1：
```Shell
root@NekoServer:~# npx envinfo --system --binaries --browsers

  System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 DO-Premium-Intel
    Memory: 886.35 MB / 1.92 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.4 - /usr/bin/pnpm

root@NekoServer:~#
```

Server 2：
```shell
root@RainYun-cAI2P5IC:/opt/mx-space/Shiro# npx envinfo --system --binaries --browsers
Need to install the following packages:
envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Memory: 13.42 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.5.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.0 - /usr/bin/npm
    pnpm: 8.9.0 - /usr/bin/pnpm

root@RainYun-cAI2P5IC:/opt/mx-space/Shiro#
```

Server 3：
```shell
root@138:~# npx envinfo --system --binaries --browsers
Need to install the following packages:
envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) arm64 Neoverse-N1
    Memory: 6.62 GB / 8.00 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    npm: 10.1.0 - /usr/bin/npm

npm notice 
npm notice New minor version of npm available! 10.1.0 -> 10.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.0
npm notice Run npm install -g npm@10.2.0 to update!
npm notice 
root@138:~#
```

三台服务器 Docker 均使用 `get.docker.com` 的脚本安装，均使用的是该仓库中的 `docker-compose.yml`

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Shiro 没有登陆态，看上去你的 Shiro, admin 不在同一个域，可以双击 shiro header 的左边的头像进行登录。

**Comment by BLxcwg666** [comment]
> Shiro 没有登陆态，看上去你的 Shiro, admin 不在同一个域，可以双击 shiro header 的左边的头像进行登录。  

也就是说 shiro 和 admin 要在同一个域才能自动登录吗

**Comment by Innei** [comment]
现在可以通过接入 clerk owner 的 userid 登入。
