### ISSUE TITLE
博文阅读数量计算不准确

### ISSUE THREAD

**Issue by zhuozhiyongde** [mx-space/core#1151]
### Describe the bug

如题，目前定位的猜测原因是：
客户端访问了前端 Shiro 博文 URL，如 https://arthals.ink/posts/experience/attack-lab 的同时没有和后端沟通，是服务器上的 Next.js 同后端进行的沟通（服务端渲染），即反向代理前端的服务端 2323 端口会请求反向代理后端 API 地址的服务器 2333 端口的 https://api.arthals.ink/api/v2/posts/experience/attack-lab 。这导致后端访问日志中一直只能看到服务器自己的 IP 在请求 API ，也就导致了阅读量的计算不准确。经过尝试，我发现此问题和前后端是否设置 XFF/XRP 头部没有任何关系。

我希望能够直接将阅读量改为按照请求次数计数，这样就能解决这个问题了（否则前端 Shiro 更改渲染模式我估计会更加难以实现）

同时，我注意到，在 mx-admin 页面的数据-访问路径这个列表并不会随着切换页码而刷新，必须切换页码后再次刷新页面才能更新（即使URL参数已经改变至 https://api.arthals.ink/proxy/qaqdmin#/analyze?page=2 ，但是显示的依旧是https://api.arthals.ink/proxy/qaqdmin#/analyze?page=1 的内容）

### Reproduction

打开控制台和后台刷新试试即可复现

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
    Memory: 5.75 GB / 7.25 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhuozhiyongde** [comment]
似乎 API 相关应当是 core 的问题，抱歉

**Comment by zhuozhiyongde** [comment]
也许只用移除 `apps/core/src/processors/helper.counting.service.ts` 的 `isReadBefore()` 函数与相关判断逻辑。
但是简单这样做的话还是无法准确记录 IP，或许可以让 Shiro 请求的时候带上真实 IP 或者让客户端来发起请求？因为显然 mx-core 不是只有 Shiro 一家在用。这么做也有弊端，就是对于校园网下公共 IP 仍会计数不准确
应当怎么修改还是大佬来权衡吧，我是倾向于移除相关”阅读过“的逻辑同时，让前端来请求，这样就既可以记录访问 IP，也不用担心相同IP不重复计数的问题，只是这么做就会导致可以刷浏览量，不过反正是我自己的站，也没多少人看，只要我自己不刷，估计也没人刷，刷高了我还高兴（hhh

**Comment by Innei** [comment]
已重构，更新到最新的 core 和 shiro。另外 admin 的问题也修复

**Comment by zhuozhiyongde** [comment]
感谢群主！
