### ISSUE TITLE
[Bug] Bark notifier not work

### ISSUE THREAD

**Issue by zhuozhiyongde** [mx-space/core#1327]
### Describe the bug

如题，Bark 通知现在似乎是不可用状态。

设置了正确的 Device ID，尝试填写服务器 URL 为 `https://api.day.app/ `或者 `https://day.app/ `，测试评论，通知均不可用。

值得一提的是，这个 `https://day.app/` 默认值似乎并不生效：

![image](https://github.com/mx-space/core/assets/36695271/083222be-baad-4563-8119-b8ad4a3212c3)

### Reproduction

As desc.

### System Info

```Shell
No need.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
`https://api.day.app`

**Comment by zhuozhiyongde** [comment]
> `https://api.day.app`

似乎也不生效...

**Comment by Innei** [comment]
没有复现。看下浏览器请求

**Comment by zhuozhiyongde** [comment]
> 没有复现。看下浏览器请求

在博文页面评论网络请求一切正常，POST 返回 201 Created

docker 日志如下：

![Cleanshot-2024-01-03-at-00 40 27@2x](https://github.com/mx-space/core/assets/36695271/fb1af094-801f-4979-b86c-49d045cb2420)

顺带一提，现在的 IP 查询功能似乎是完全的寄了，每个 IP 都看不了，可能是 API 变更了（？

@Innei

**Comment by zhuozhiyongde** [comment]
更新：已经解决，完全是设置的锅，填成了 Device Token 而不是示例 URL 中的 Key...

或许可以更新下文档说明一下这个问题，以及 URL 最后一定不能带 /，我想其实应该可以修改一下默认值？
