### ISSUE TITLE
无法查看已读的评论

### ISSUE THREAD

**Issue by YuziO2** [mx-space/core#1334]
### Describe the bug

与 #1232 症状类似，但只有已读页报错。
![image](https://github.com/mx-space/core/assets/50757904/867c6159-e19a-4eab-b414-7c8af49ae097)
![image](https://github.com/mx-space/core/assets/50757904/e33f7f9b-14f7-424b-91ff-5e0ba0073c2c)
版本为最新：
![image](https://github.com/mx-space/core/assets/50757904/aa85338e-5632-4457-869e-7dc66f1b3150)

### Reproduction

在管理面板中点击评论选项卡->点击已读

### System Info

```Shell
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
    Memory: 128.89 MB / 919.82 MB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CielNeko** [comment]
我这无法复现 不知道什么魔法

**Comment by Innei** [comment]
看起来是你的数据库数据坏了，没有做数据库的迁移。这个迁移过程应该是自动，不知道为什么你没有迁移完全

**Comment by Innei** [comment]
看看启动日志有没有出现 `v4.6.2 migration failed`

**Comment by YuziO2** [comment]
> 看看启动日志有没有出现 `v4.6.2 migration failed`

没有出现，所以我该如何修复呢？

**Comment by Innei** [comment]
你的数据是怎么来的。

**Comment by Innei** [comment]
你是通过后续更新之后出现的问题？

**Comment by YuziO2** [comment]
> 你的数据是怎么来的。

有一次通过备份转移到了另一台主机上

**Comment by YuziO2** [comment]
> 你是通过后续更新之后出现的问题？

我记得这个问题出现有一段时间了

**Comment by Innei** [comment]
数据迁移出问题了。进 mongosh 把 `migrations` 这个 collection 删了，重启 app

**Comment by YuziO2** [comment]
migaration的样子：
![image](https://github.com/mx-space/core/assets/50757904/867e3536-885a-415d-9343-566b48f741a8)
drop后死循环报错：
![image](https://github.com/mx-space/core/assets/50757904/77b9ff86-7a0e-4925-aab5-6f19fc9b98c3)

**Comment by YuziO2** [comment]
修好了，我把4.6.0又给手动insert回去，它就好了。
`db.migrations.insertOne({_id: ObjectId('65950ed49e50392be841e1de'),name: 'v4_6_0',time:1704267476150})`
然后评论也能看了，估计是正确运行了`v4.6.2`的迁移脚本吧。
![image](https://github.com/mx-space/core/assets/50757904/dcaed38b-fea4-488c-82a9-8d4c3ba74e29)

**Comment by YuziO2** [comment]
估计是备份的时候是旧版本的，然后直接恢复在了新版本的系统上，导致迁移脚本没有运行，作者大大是否可以考虑一下修复这样的边缘情况？🤔

**Comment by Innei** [comment]
嗯,在后续版支持了
