### ISSUE TITLE
建议支持自定义 Gravatar 源

### ISSUE THREAD

**Issue by BLxcwg666** [mx-space/core#1400]
### Clear and concise description of the problem

如题  
cravatar 有时候不是很好用（

### Suggested solution

在设置里面加一个选项，让用户自定义 Gravatar 镜像源

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
PR welcome
