### ISSUE TITLE
Passkey无法正常录入、后台地址无法自定义、教程文档内容需修正

### ISSUE THREAD

**Issue by h1k4r** [mx-space/core#1407]
### Describe the bug

1. Passkey无法正常录入

环境如图
![image](https://github.com/mx-space/core/assets/60561049/40d0b2f9-1c88-400b-92b7-68e4bdadc6b5)

Windows正常录入密钥
![image](https://github.com/mx-space/core/assets/60561049/d8931267-364b-4d86-9fcf-c604651a255f)

后台报错
![image](https://github.com/mx-space/core/assets/60561049/55406262-b891-4ef9-a011-771d7cd7570d)

2.后台地址无法自定义
系统初始化的时候可以输入后台地址路径，那为啥子没办法改后台地址
![image](https://github.com/mx-space/core/assets/60561049/8bb7df98-fcd3-4287-b459-da73159985e0)
![image](https://github.com/mx-space/core/assets/60561049/f9cef0af-8269-4f78-b631-3d5e592679fa)

3.教程文档内容需修正
我是一个了解mx-space存在但是是没用过的人，照着教程弄了很久第一次打开后端依旧还是提示
```
{
    "ok": 0,
    "message": "Cannot GET /"
}
```
在我翻遍文档无果后Google了一番才发现原来有 `/qwqadmin` 这一个管理后台的入口，而我在教程文档里没有看到，再三阅览，我发现了这段话
![c981e457f347c4fd16818b11e31cef6](https://github.com/mx-space/core/assets/60561049/811e16b7-7ac5-4edf-ac76-d475cc3c03f8)
我说你们。。。真的很歧视小白吗？
另外再建议当issue累积到一个程度后可以开一个报错专栏，方便萌新知道是哪出了问题
以上就是所有的内容。

### Reproduction

有附图

### System Info

```Shell
Linux VM-8-17-centos 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by h1k4r** [comment]
我还有。。高德api无法录入
![image](https://github.com/mx-space/core/assets/60561049/5fb8b380-8c00-4d9d-a8b6-8b721b01fd43)
他就是这么长啊。。还能怎么短

**Comment by wuhang2003** [comment]
> 我说你们。。。真的很歧视小白吗？

因为已经在[反向代理](https://mx-space.js.org/docs/extra#%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)的后面给了两种反代方式所对应的后台地址，所以没有在后端部署这部分提供。不过文档没加反向代理的链接是个问题
![image](https://github.com/mx-space/core/assets/108316419/8e36abf3-4420-4833-9126-d3956af937c8)
![image](https://github.com/mx-space/core/assets/108316419/ec40e6ef-8e58-47ab-ab15-5121db623e84)

**Comment by h1k4r** [comment]
> > 我说你们。。。真的很歧视小白吗？
> 
> 因为已经在[反向代理](https://mx-space.js.org/docs/extra#%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)的后面给了两种反代方式所对应的后台地址，所以没有在后端部署这部分提供。不过文档没加反向代理的链接算是个问题 ![image](https://private-user-images.githubusercontent.com/108316419/300455237-8e36abf3-4420-4833-9126-d3956af937c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzI1NjQsIm5iZiI6MTcwNjUzMjI2NCwicGF0aCI6Ii8xMDgzMTY0MTkvMzAwNDU1MjM3LThlMzZhYmYzLTQ0MjAtNDgzMy05MTI2LWQzOTU2YWY5MzdjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMjQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjMxZTliNjM0MmI2OGFmMDk1ZDMwNGQzN2MyYTRlOGJkNDQ4MTJmOTlhYmI5ZGU0MDllODYwMjVjZmM0MDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_1pmgK5dd1Twoa4z32wZcnBXqUg2a9FRGuOIz_Rb1o) ![image](https://private-user-images.githubusercontent.com/108316419/300455365-ec40e6ef-8e58-47ab-ab15-5121db623e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzI1NjQsIm5iZiI6MTcwNjUzMjI2NCwicGF0aCI6Ii8xMDgzMTY0MTkvMzAwNDU1MzY1LWVjNDBlNmVmLThlNTgtNDdhYi1hYjE1LTUxMjFkYjYyM2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMjQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFjNzQxMTdmZjM5N2FlNDI3YTdmMzUzN2IzYTUyMmU5N2M4NzJmNDQ5NjY3MzA2OTA1NjVkYmU5M2QwZTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0KG13b9uqZoRCvshtrFZ8zW1v1LFIwz-IwEJ8jBHP3c)

这个怪我没看仔细，没往下划。权当建议在部署环境这一节中补充说明吧。
还有就是我不太明白，本地后台和后台有什么区别？

**Comment by wuhang2003** [comment]
> 这个怪我没看仔细，没往下划。权当建议在部署环境这一节中补充说明吧。 还有就是我不太明白，本地后台和后台有什么区别？

后台引用 jsd 的资源，本地后台引用自己的资源

**Comment by h1k4r** [comment]
> > > > 我说你们。。。真的很歧视小白吗？
> > > 
> > > 
> > > 因为已经在[反向代理](https://mx-space.js.org/docs/extra#%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)的后面给了两种反代方式所对应的后台地址，所以没有在后端部署这部分提供。不过文档没加反向代理的链接算是个问题 ![image](https://private-user-images.githubusercontent.com/108316419/300455237-8e36abf3-4420-4833-9126-d3956af937c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzI1NjQsIm5iZiI6MTcwNjUzMjI2NCwicGF0aCI6Ii8xMDgzMTY0MTkvMzAwNDU1MjM3LThlMzZhYmYzLTQ0MjAtNDgzMy05MTI2LWQzOTU2YWY5MzdjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMjQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjMxZTliNjM0MmI2OGFmMDk1ZDMwNGQzN2MyYTRlOGJkNDQ4MTJmOTlhYmI5ZGU0MDllODYwMjVjZmM0MDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_1pmgK5dd1Twoa4z32wZcnBXqUg2a9FRGuOIz_Rb1o) ![image](https://private-user-images.githubusercontent.com/108316419/300455365-ec40e6ef-8e58-47ab-ab15-5121db623e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzI1NjQsIm5iZiI6MTcwNjUzMjI2NCwicGF0aCI6Ii8xMDgzMTY0MTkvMzAwNDU1MzY1LWVjNDBlNmVmLThlNTgtNDdhYi1hYjE1LTUxMjFkYjYyM2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMjQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFjNzQxMTdmZjM5N2FlNDI3YTdmMzUzN2IzYTUyMmU5N2M4NzJmNDQ5NjY3MzA2OTA1NjVkYmU5M2QwZTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0KG13b9uqZoRCvshtrFZ8zW1v1LFIwz-IwEJ8jBHP3c)
> > 
> > 
> > 这个怪我没看仔细，没往下划。权当建议在部署环境这一节中补充说明吧。 还有就是我不太明白，本地后台和后台有什么区别？
> 
> 后台引用 jsd 的资源，本地后台引用自己的资源

好的！了解了

**Comment by h1k4r** [comment]
> > > > > 我说你们。。。真的很歧视小白吗？
> > > > 
> > > > 
> > > > 因为已经在[反向代理](https://mx-space.js.org/docs/extra#%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)的后面给了两种反代方式所对应的后台地址，所以没有在后端部署这部分提供。不过文档没加反向代理的链接算是个问题 ![image](https://private-user-images.githubusercontent.com/108316419/300455237-8e36abf3-4420-4833-9126-d3956af937c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzI1NjQsIm5iZiI6MTcwNjUzMjI2NCwicGF0aCI6Ii8xMDgzMTY0MTkvMzAwNDU1MjM3LThlMzZhYmYzLTQ0MjAtNDgzMy05MTI2LWQzOTU2YWY5MzdjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMjQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjMxZTliNjM0MmI2OGFmMDk1ZDMwNGQzN2MyYTRlOGJkNDQ4MTJmOTlhYmI5ZGU0MDllODYwMjVjZmM0MDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_1pmgK5dd1Twoa4z32wZcnBXqUg2a9FRGuOIz_Rb1o) ![image](https://private-user-images.githubusercontent.com/108316419/300455365-ec40e6ef-8e58-47ab-ab15-5121db623e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzI1NjQsIm5iZiI6MTcwNjUzMjI2NCwicGF0aCI6Ii8xMDgzMTY0MTkvMzAwNDU1MzY1LWVjNDBlNmVmLThlNTgtNDdhYi1hYjE1LTUxMjFkYjYyM2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMjQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFjNzQxMTdmZjM5N2FlNDI3YTdmMzUzN2IzYTUyMmU5N2M4NzJmNDQ5NjY3MzA2OTA1NjVkYmU5M2QwZTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0KG13b9uqZoRCvshtrFZ8zW1v1LFIwz-IwEJ8jBHP3c)
> > > 
> > > 
> > > 这个怪我没看仔细，没往下划。权当建议在部署环境这一节中补充说明吧。 还有就是我不太明白，本地后台和后台有什么区别？
> > 
> > 
> > 后台引用 jsd 的资源，本地后台引用自己的资源
> 
> 好的！了解了

![image](https://github.com/mx-space/core/assets/60561049/eb3b6fd1-3c66-4e27-b122-00893c056eaf)
但好像不怎么有用

**Comment by Innei** [comment]
另外不能通过直接修改后台路径的方式去修改实际的地址。这是做不到的。这个让你填写是为了你可以部署一个其他的面板去指向。

**Comment by h1k4r** [comment]
> 另外不能通过直接修改后台路径的方式去修改实际的地址。这是做不到的。这个让你填写是为了你可以部署一个其他的面板去指向。

好的，剩下的就是Passkey的问题和我这个本地后台的问题了。我先前重装了几次亦是如此，希望能复现一下

**Comment by Innei** [comment]
`extractStrings is not a function` 之前谁提过，issue 里找不到了。是 ncc 打包的问题。在 env 注入 CBOR_NATIVE_ACCELERATION_DISABLED=true 就行了

**Comment by Innei** [comment]
https://simplewebauthn.dev/docs/packages/server#error-extractstrings-is-not-a-function

**Comment by h1k4r** [comment]
> `extractStrings is not a function` 之前谁提过，issue 里找不到了。是 ncc 打包的问题。在 env 注入 CBOR_NATIVE_ACCELERATION_DISABLED=true 就行了

好，那高德地图api的key length呢

**Comment by h1k4r** [comment]
> > `extractStrings is not a function` 之前谁提过，issue 里找不到了。是 ncc 打包的问题。在 env 注入 CBOR_NATIVE_ACCELERATION_DISABLED=true 就行了
> 
> 好，那高德地图api的key length呢

本地后台的资源404我试了很多路径都没办法从前台打开，不知是否是设计缺陷

**Comment by Innei** [comment]
> extractStrings is not a function 之前谁提过，issue 里找不到了。是 ncc 打包的问题。在 env 注入 CBOR_NATIVE_ACCELERATION_DISABLED=true 就行了

这个问题现在修下，默认的 env 注入值有点问题

**Comment by Innei** [comment]
其他问题没有复现。

**Comment by Innei** [comment]
`extractStrings is not a function` 现在应该得到解决

**Comment by h1k4r** [comment]
> `extractStrings is not a function` 现在应该得到解决

我现在还在重装

**Comment by wuhang2003** [comment]
> 本地后台的资源404我试了很多路径都没办法从前台打开，不知是否是设计缺陷

除了本地后台之外还有其他 404 吗？初步推测可能是反向代理配置的问题

**Comment by h1k4r** [comment]
> > 本地后台的资源404我试了很多路径都没办法从前台打开，不知是否是设计缺陷
> 
> 除了本地后台之外还有其他 404 吗？初步推测可能是反向代理配置的问题

没了，就静态资源调用404

**Comment by h1k4r** [comment]
我大概处理好这个静态问题了，但是不知道原先为什么会失效。
我先是在宝塔配置好反代之后注释掉反代配置，然后再加入文档里的反代配置，现在已可以成功打开。

- 只是初始化需要自定义接口地址了，不知何故

**Comment by wuhang2003** [comment]
> 我大概处理好这个静态问题了，但是不知道原先为什么会失效。 我先是在宝塔配置好反代之后注释掉反代配置，然后再加入文档里的反代配置，现在已可以成功打开。
> 
> * 只是初始化需要自定义接口地址了，不知何故

实际上文档是有说用面板的建议先在面板加反代再复制对应的片段到反代配置的内容的（
没记错的话自定义接口地址后再进去应该能用后台了吧

**Comment by h1k4r** [comment]
> > 我大概处理好这个静态问题了，但是不知道原先为什么会失效。 我先是在宝塔配置好反代之后注释掉反代配置，然后再加入文档里的反代配置，现在已可以成功打开。
> > 
> > * 只是初始化需要自定义接口地址了，不知何故
> 
> 实际上文档是有说用面板的建议先在面板加反代再复制对应的片段到反代配置的内容的（ 没记错的话自定义接口地址后再进去应该能用后台了吧

已正常

**Comment by h1k4r** [comment]
收到后台更新了喵

**Comment by h1k4r** [comment]
> 收到后台更新了喵

但是高德问题没解决

**Comment by wuhang2003** [comment]
> 但是高德问题没解决

高德这边尝试了一下是没问题的，确认 Key 绑定的是 Web 服务吗？

**Comment by h1k4r** [comment]
> > 但是高德问题没解决
> 
> 高德这边尝试了一下是没问题的，确认 Key 绑定的是 Web 服务吗？

面板版本: 3.36.3
还是Invalid key length

**Comment by h1k4r** [comment]
![1706624522812](https://github.com/mx-space/core/assets/60561049/2bf6de2c-e2a5-4dc0-a554-f5311ba743ee)
没毛病啊

**Comment by wuhang2003** [comment]
> > > 但是高德问题没解决
> > 
> > 
> > 高德这边尝试了一下是没问题的，确认 Key 绑定的是 Web 服务吗？
> 
> 面板版本: 3.36.3 还是Invalid key length

试了一下你的 Key 是没问题的，可以正常修改。
要不就是你设置里面有其他 Key 没填没保存？
还有看图开了广告过滤，排除过广告过滤了吗？

**Comment by h1k4r** [comment]
> > > > 但是高德问题没解决
> > > 
> > > 
> > > 高德这边尝试了一下是没问题的，确认 Key 绑定的是 Web 服务吗？
> > 
> > 
> > 面板版本: 3.36.3 还是Invalid key length
> 
> 试了一下你的 Key 是没问题的，可以正常修改。 要不就是你设置里面有其他 Key 没填没保存？ 还有看图开了广告过滤，排除过广告过滤了吗？

adg没拦截到我这，我重新拉取镜像更新过了亦是如此，犯毛病了。这个问题你们那边修复好了就行，我对这个功能需求不大，只是需要反馈一下。十分感谢啦

**Comment by wuhang2003** [comment]
> adg没拦截到我这，我重新拉取镜像更新过了亦是如此，犯毛病了。这个问题你们那边修复好了就行，我对这个功能需求不大，只是需要反馈一下。十分感谢啦

主要我们这边有复现了才能修啊，体质问题复现不了的也没法算命（

**Comment by h1k4r** [comment]
> > adg没拦截到我这，我重新拉取镜像更新过了亦是如此，犯毛病了。这个问题你们那边修复好了就行，我对这个功能需求不大，只是需要反馈一下。十分感谢啦
> 
> 主要我们这边有复现了才能修啊，体质问题复现不了的也没法算命（

带胶布带胶布 你们解决就好啦 辛苦你们了！

**Comment by Innei** [comment]
https://mx-space.js.org/usage/security.html#%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94
