### ISSUE TITLE
[v5] 删掉 cos 换 s3

### ISSUE THREAD

**Issue by Innei** [mx-space/core#1438]

**Comment by Innei** [comment]
https://www.bitiful.com/

**Comment by Innei** [comment]
https://www.lightcdn.com/

**Comment by Innei** [comment]
https://www.dogecloud.com/price?product=oss

**Comment by BLxcwg666** [comment]
还是留着吧，有人会用（比如我x

**Comment by Innei** [comment]
> 还是留着吧，有人会用（比如我x

不留了，化繁为简。你可以停留在 v4

**Comment by Innei** [comment]
COS SDK 烂的要死 找不想用了

**Comment by TinsFox** [comment]
这些对象存储好像都会支持 s3 协议，这样是不是可以不需要管用户用什么了🤔

**Comment by Innei** [comment]
之后再说吧
