### ISSUE TITLE
关于api-client接口select字段的疑问

### ISSUE THREAD

**Issue by orion-tan** [mx-space/core#1520]
### 我在开发一个 mx-space 的前端主题，对 api-client 接口里面 select 选项有点疑问和建议，希望大佬可以解惑。

疑问：
1. select中 +xxx 和 -xxx 是什么作用？我测试post接口无论使用 + 还是 - ，接口返回都只有id字段。不使用 + 或者 - ，返回的是正确的已选择字段，不清楚是不是bug。

建议：
1. 接口返回值可以根据 select 内选择的字段自动 Pick<PostModel> 内字段，类似 primsa select 那样。

**Comment by Innei** [comment]
具体是哪个接口. post 接口是不会消费 select 的, 因为这个场景没有必要.

另外, `select` 字段参考 mongoose 的 `select`

**Comment by orion-tan** [comment]
post.getList(page,perPage,opts)接口

获取列表感觉是有必要的，列表只需要少量信息，文章内容不需要获取。

**Comment by Innei** [comment]
`getList` 这个接口目前不支持 `+` `-` 的 `select`，这里查询我没用 mongoose 的而不是走了管道。所以只能传你想要的具体的字段。比如 `select: 'title _id id created modified slug categoryId copyright tags count pin meta'`

**Comment by orion-tan** [comment]
好的，感谢大佬。
