### ISSUE TITLE
支持 M2 arm docker 部署

### ISSUE THREAD

**Issue by TinsFox** [mx-space/core#1522]
### Clear and concise description of the problem

我想要在本地的 Apple M2 上部署 mx-sapce 🤪

### Suggested solution

请提供一个 arm 的 docker image 🫡

### Additional context

跟着[文档](https://mx-space.js.org/docs/docker)

无法运行起来，貌似是现在的镜像不支持在 arm 上面运行

<img width="798" alt="image" src="https://github.com/mx-space/core/assets/33956589/048ab39c-60bc-4a37-858b-ead8e8c75493">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
本地运行先跑 docker build 本地打 docker image
