### ISSUE TITLE
[Bug] Docker 5.2.0 版本需要手动触发 Publish

### ISSUE THREAD

**Issue by zhuozhiyongde** [mx-space/core#1523]
### Describe the bug

-

### Reproduction

-

### System Info

```Shell
no need
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
从新发版了
