### ISSUE TITLE
删除文章后不会在xlog上删除

### ISSUE THREAD

**Issue by BLxcwg666** [mx-space/core#1583]
### Describe the bug

如题  
在 mx-admin 后台删除已经同步到 xlog 的文章，在 xlog 的这篇文章不会随着 mx space 的删除而删除

### Reproduction

新建文章，发布，同步到 xlog，删除文章，查看 xlog

### System Info
System：
```Shell

root@Nya:/opt/mx-space/core# npx envinfo --system --binaries --browsers
Need to install the following packages:
  envinfo@7.11.1
Ok to proceed? (y) y

  System:
    OS: Linux 6.7 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
    Memory: 2.28 GB / 3.83 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm

root@Nya:/opt/mx-space/core#
```

API：
```
{"name":"@mx-space/core","author":"Innei <https://innei.ren>","version":"5.4.4","homepage":"https://github.com/mx-space/core#readme","issues":"https://github.com/mx-space/core/issues"}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
这个需求暂时不考虑，PR welcome
