### ISSUE TITLE
按照官网 docker 部署完成，并完成 /qaqdmin#/setup 填写初始化信息，还是无法进入后台

### ISSUE THREAD

**Issue by parteecat** [mx-space/core#1619]
### Describe the bug

目前已经重新部署了两次，仍然是无法进入后台
![image](https://github.com/mx-space/core/assets/37294237/6e1f4cf6-c755-44ea-b222-6797f0842f71)

### Reproduction

按照官网 https://mx-space.js.org/docs/docker 部署并完成 /qaqdmin#/setup 初始化就会出现

### System Info

```Shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 87.70 MB / 1.95 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.9.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 7.21.1 - /usr/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wuhang2003** [comment]
使用`/proxy/qaqdmin`设置初始化看看（

**Comment by parteecat** [comment]
> 使用`/proxy/qaqdmin`设置初始化看看（

很奇怪呢，目前一直卡 loading，进不去登录页或者后台，也没办法重新设置。初始设置是使用默认填写的地址，也是没有改动什么
![image](https://github.com/mx-space/core/assets/37294237/a0a30005-80c7-4c95-b1ee-ab2e592da42a)

**Comment by wuhang2003** [comment]
容器 log 看一下

**Comment by Innei** [comment]
很奇怪为什么你的请求是 403 的

**Comment by Innei** [comment]
你这个应该是初始化已经完成了，直接 `/proxy/qaqdmin` 也进不去？

**Comment by parteecat** [comment]
> 你这个应该是初始化已经完成了，直接 `/proxy/qaqdmin` 也进不去？

不行呢，会重定向到 #/setup

**Comment by parteecat** [comment]
> 容器 log 看一下

[root@VM-24-15-centos ~]# docker logs 392d4e2e471078db8d8f0bb55ab3583641ccd4091f2ad632585874d1810a261a
[Nest] 1  - 04/13/2024, 9:06:16 PM     LOG 数据目录已经建好：/root/.mx-space
[Nest] 1  - 04/13/2024, 9:06:16 PM     LOG 临时目录已经建好：/tmp/mx-space
[Nest] 1  - 04/13/2024, 9:06:16 PM     LOG 日志目录已经建好：/root/.mx-space/log
[Nest] 1  - 04/13/2024, 9:06:16 PM     LOG 资源目录已经建好：/root/.mx-space/assets
[Nest] 1  - 04/13/2024, 9:06:16 PM     LOG 文件存放目录已经建好：/root/.mx-space/static
[Nest] 1  - 04/13/2024, 9:06:16 PM     LOG 文件回收站目录已经建好：/tmp/mx-space/trash
cwd:  /app
[Database] migrate v200Alpha1
[Database] migrate v3330
[Database] migrate v3360
[Database] migrate v3390
[Database] migrate v4_6_0
[Database] migrate v4_6_0__4
[Database] migrate v4.6.2__0
[Database] migrate v5.0.0-1
[Database] migrate v5.1.1
ℹ ENV: production
✔ [P1] Server listen on: http://127.0.0.1:2333
✔ [P1] Admin Local Dashboard: http://127.0.0.1:2333/proxy/qaqdmin
ℹ [P1] If you want to debug local dev dashboard on production environment with https domain, you can go to: https://<your-prod-domain>/proxy/qaqdmin/dev-proxy
ℹ Server is up. +2647ms

 WARN   [EmailService]  未启动邮件通知 


 WARN   [AllExceptionsFilter]  IP: 172.18.0.1 错误信息：(500) 站点主人信息已丢失 Path: /api/v2/master?t=1713014656457 


 WARN   [AllExceptionsFilter]  IP: 172.18.0.1 错误信息：(403) Forbidden resource Path: /api/v2/init?t=1713014734040 


 WARN   [AllExceptionsFilter]  IP: 172.18.0.1 错误信息：(403) Forbidden resource Path: /api/v2/init?t=1713014734178 


 WARN   [AllExceptionsFilter]  IP: 172.18.0.1 错误信息：(403) Forbidden resource Path: /api/v2/init?t=1713014734271 


 WARN   [AllExceptionsFilter]  IP: 172.18.0.1 错误信息：(403) Forbidden resource Path: /api/v2/init?t=1713014734322 


 WARN   [AllExceptionsFilter]  IP: 172.18.0.1 错误信息：(403) Forbidden resource Path: /api/v2/init/configs/default?t=1713014734322

**Comment by wuhang2003** [comment]
@TerraTr3k 才发现你环境本身就有问题（
`OS: Linux 3.10 CentOS Linux 7 (Core)`
![image](https://github.com/mx-space/core/assets/108316419/38380f7d-04d8-48b9-924b-0dd523f0ddd9)
~~建议别用 CentOS~~

**Comment by Innei** [comment]
从这两条日志非常矛盾。

```
WARN [AllExceptionsFilter] IP: 172.18.0.1 错误信息：(500) 站点主人信息已丢失 Path: /api/v2/master?t=1713014656457

WARN [AllExceptionsFilter] IP: 172.18.0.1 错误信息：(403) Forbidden resource Path: /api/v2/init?t=1713014734040


```

我来解释一下：

`/api/v2/init` 403 的情况只有当你完成首次用户注册之后才会 403。出现 403 只能说明你已经完成了初始化。


`/api/v2/master` 500站点主人信息已丢失  说明当前表里一个用户也不存在，所以很矛盾，除非手动修改了 db 数据 其他我没想到会出现这个 case

**Comment by FoskyM** [comment]
我也遇到了这个问题，但是我重启容器后就正常了（奇怪）。

**Comment by Lks7** [comment]
> 我也遇到了这个问题，但是我重启容器后就正常了（奇怪）。

此方法有用，重启之后就好了

**Comment by sharkbear212** [comment]
> 我也遇到了这个问题，但是我重启容器后就正常了（奇怪）。

这个真的有用

**Comment by Innei** [comment]
Fixed
