### ISSUE TITLE
后台无法上传文件，选择文件后没有上传按钮，页面也没有响应

### ISSUE THREAD

**Issue by solomon-cc** [mx-space/core#1635]
### Describe the bug

后台无法上传文件，选择文件后没有上传按钮，页面也没有响应
![image](https://github.com/mx-space/core/assets/25998534/fa766aba-e811-4dea-ae54-53b09e8f51aa)

### Reproduction

后台无法上传文件，选择文件后没有上传按钮，页面也没有响应

### System Info

```Shell
面板版本: 4.2.5

系统版本：5.5.5
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Fixed

**Comment by solomon-cc** [comment]
> Fixed

貌似不行。虽然从前台点击删除，显示删除成功。但刷新后文件还存在，后台服务日志报错如下？：
```
 ERROR   [System]  删除文件失败 ENOENT: no such file or directory, rename '/root/.mx-space/static/file/dkx02yofnnkumh8bjl.md' -> '/root/.mx-space/trash/dkx02yofnnkumh8bjl.md'

 FileService
```

![image](https://github.com/mx-space/core/assets/25998534/213ffa9a-36b3-47ad-9941-4b6b7f82d05c)
![image](https://github.com/mx-space/core/assets/25998534/cb047064-4c29-4e26-939d-016268ad6ff8)

**Comment by solomon-cc** [comment]
> Fixed

看了下代码报错，是做了rename操作。如果/root/.mx-space/trash 路径不存在，就会报上面的错。我手动创建该目录后，再次操作就可以了。
