### ISSUE TITLE
后台备份设置bucket相关信息后，从前台编辑文章点击图片上传报错。

### ISSUE THREAD

**Issue by solomon-cc** [mx-space/core#1639]
### Describe the bug

![image](https://github.com/mx-space/core/assets/25998534/236bc765-f9a7-441e-87b1-bb08d8c179ba)
配置后，点击保存。刷新页面后，SecretKey为空，估计后台没有保存上。、
shiro报错信息：
`⨯ InvalidArgument: Invalid Argument: Credential access key has length 0, should be 32
    at throwDefaultError (/app/node_modules/.pnpm/@smithy+smithy-client@2.5.1/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /app/node_modules/.pnpm/@smithy+smithy-client@2.5.1/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/app/node_modules/.pnpm/@aws-sdk+client-s3@3.552.0/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/.pnpm/@smithy+middleware-serde@2.3.0/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /app/node_modules/.pnpm/@aws-sdk+middleware-signing@3.552.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
    at async /app/node_modules/.pnpm/@smithy+middleware-retry@2.3.1/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /app/node_modules/.pnpm/@aws-sdk+middleware-flexible-checksums@3.535.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:173:18
    at async /app/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.552.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
    at async /app/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.552.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14 {`

### Reproduction

admin后台点击文件上传，页面没有响应。文件也无法上传

### System Info

```Shell
面板版本: 4.2.7
系统版本：5.5.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
备份和文件上传没有直接关系，模块是独立的

**Comment by solomon-cc** [comment]
> 备份和文件上传没有直接关系，模块是独立的

那文件上传报错是什么情况呢？

**Comment by solomon-cc** [comment]
> 备份和文件上传没有直接关系，模块是独立的

在前端直接粘贴图片时，提示文件没有上传到s3.点击感叹号进行上传，报错

**Comment by Innei** [comment]
Shiro 的 S3 单独配置的。和 core 没关系。另外那个我没维护了，S3 写死了我自己的。

**Comment by solomon-cc** [comment]
> Shiro 的 S3 单独配置的。和 core 没关系。另外那个我没维护了，S3 写死了我自己的。

恩。我看了源码了，自己改了从环境变量里面读取(Shiro\src\app.static.config.ts)。
![image](https://github.com/mx-space/core/assets/25998534/8f44c62c-78b6-4b3e-b6aa-38d76be98abb)
