### ISSUE TITLE
访问后端提示{"ok":0,"message":"Cannot GET /qaqdmin"}

### ISSUE THREAD

**Issue by binaryYuki** [mx-space/core#1684]
### Describe the bug

访问后端提示{"ok":0,"message":"Cannot GET /qaqdmin"}
<img width="748" alt="截屏2024-05-07 22 00 05" src="https://github.com/mx-space/core/assets/60097976/0b9b5b8c-6673-452a-a200-d09b55ba4e3a">

### Reproduction

latest

### System Info

```Shell
22.04.1-Ubuntu 
Docker version 26.1.1, build 4cf5afa
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghost** [comment]
访问 /proxy/qaqdmin

**Comment by binaryYuki** [comment]
感谢！
