### ISSUE TITLE
[Bug] docker 环境下无法启动

### ISSUE THREAD

**Issue by BLxcwg666** [mx-space/core#1712]
### Describe the bug

如题，使用 `docker compose pull && docker compose up -d` 更新后端后 core 容器无法启动  
![image](https://github.com/mx-space/core/assets/66854530/5ceb071e-aa96-48a0-9605-0b0f13cc5e6f)
![image](https://github.com/mx-space/core/assets/66854530/c7b1b0c4-fab9-48fc-b203-6fda95e04cb9)

  
在 docker 下的 redis 应该是另一个独立的容器，但是看起来 core 好像在尝试连接 `127.0.0.1` 的 redis，  
虽然知道问题，但是鉴于在容器底下我不会搞

### Reproduction

docker compose pull && docker compose up -d

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 938.95 MB / 1.80 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: 8.15.3 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.105
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wuhang2003** [comment]
更新 compose 文件了吗？
> 自 Core v5.7.5 版本开始，Docker 相关配置发生重大变化，请重新阅读文档（尤其是填入配置文件环节，配置有所变化）

**Comment by BLxcwg666** [comment]
对不起没看
