### ISSUE TITLE
GitHub API 存在速率限制

### ISSUE THREAD

**Issue by MSDNicrosoft** [mx-space/core#1758]
### Describe the bug

如图，在 Mix Space 管理界面点击更新面板时出现错误
![image](https://github.com/mx-space/core/assets/69967436/e3bcf4b3-31a6-437e-906a-3ae0016d87d7)

日志
![image](https://github.com/mx-space/core/assets/69967436/02af6d76-d4ee-44a4-86de-25f7bea21ea2)

可以添加一个 GITHUB_TOKEN 的环境变量，允许用户使用自己的 TOKEN 以绕过基本限制

### Reproduction

登录管理界面 -> 仪表盘 -> 页面底部的【更新面板】按钮

### System Info

```Shell
NPX

  System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 3.66 GB / 7.89 GB
  Binaries:
    Node: 20.12.2 - ~\.version-fox\cache\node\v-20.12.2\nodejs-20.12.2\node.EXE
    npm: 10.5.0 - ~\.version-fox\cache\node\v-20.12.2\nodejs-20.12.2\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
```

API
```json
{
    "name": "@mx-space/core",
    "author": "Innei <https://innei.in>",
    "version": "5.8.0",
    "homepage": "https://github.com/mx-space/core/tree/master/apps/core#readme",
    "issues": "https://github.com/mx-space/core/issues"
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Supported in #39e10efc
