### ISSUE TITLE
用户无法评论

### ISSUE THREAD

**Issue by 794681962** [mx-space/core#1780]
### Describe the bug

用户评论显示【post】https://后端地址/api/v2/comm/ <no response> failed to fetch

### Reproduction

.

### System Info

```Shell
debian 4.19
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
跨域了,手动配置信任地址

**Comment by 794681962** [comment]
不好意思大佬打扰了，能具体说一下操作步骤吗，在哪里配置信任地址？希望得到回复。感谢

**Comment by suemor233** [comment]
> 不好意思大佬打扰了，能具体说一下操作步骤吗，在哪里配置信任地址？希望得到回复。感谢

https://mx-space.js.org/docs/docker
步骤 3 ，docker-compose.yml 的 ALLOWED_ORIGINS 里填写前端域名
![CleanShot 2024-06-13 at 22 28 07@2x](https://github.com/mx-space/core/assets/89030875/05bb08c7-e150-4d71-914b-a78c66755f39)
