### ISSUE TITLE
docker 部屬遇到問題

### ISSUE THREAD

**Issue by sao-coding** [mx-space/core#1803]
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
網路說降版本可以
可以用4.4嗎?

**Comment by Innei** [comment]
没有试过，可以改下版本号试试，能正常运行一般就没事

**Comment by sao-coding** [comment]
目前看起來 OK

**Comment by wuhang2003** [comment]
mongo应该是可以降级到4.4的，但是有群友反馈在这个版本下部分功能可能存在问题
