### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by sao-coding** [mx-space/core#1804]
### Clear and concise description of the problem

i18n

### Suggested solution

i18n

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
Not plan
