### ISSUE TITLE
功能请求：对友链的宽松检查选项

### ISSUE THREAD

**Issue by edocli** [mx-space/core#1955]
### Clear and concise description of the problem

添加友链时会被强制要求https并滤掉path
（个人认为强制滤掉path不一定完全合理，因为我见过有些网站把博客放在/blog下而不是/下

我的使用情况：
恩师的个人博客尚未启用https
于是尝试使用自建的短链服务保存友链，却因为会自动删去path导致无法正常跳转

### Suggested solution

希望能在设置中提供一个选项能在自己手动添加时绕过这些检查
抑或是能在设置中提供一个修改部分功能的限制规则的地方

### Alternative

- 使用cf worker把每个友链路由到自己的（三级/四级）域名下（尚不清楚是否会被mix友链规则ban掉）
- 请恩师配置ssl证书
- ~~屑系统，这都不能修改，不用了（不是~~

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
有道理

等我有空搞下

**Comment by Innei** [comment]
![CleanShot 2024-08-08 at 11  50 54@2x](https://github.com/user-attachments/assets/a5259fb7-214d-4f59-81fa-8d24fee1a057)

已支持

**Comment by Innei** [comment]
Completed in 327d30d6756d6e172e4682428a1ca5b254852022
