### ISSUE TITLE
评论系统报错

### ISSUE THREAD

**Issue by comeweb** [mx-space/core#2001]
### Describe the bug

我从阿里云服务器搬家到HK节点服务器 在老的机器上面备份了 新的机器上还原了

然后评论系统报错 已读 第一页可以正常显示 点击其他页面会报错 
Schema hasn't been registered for model "Recently". Use mongoose.model(name, schema)

![bug1](https://github.com/user-attachments/assets/c9f66ecf-ec06-4019-9832-4d912a6cee04)

我在issues里面找到了以前有人和我一样的问题 https://github.com/mx-space/core/issues/1334 

因为老版本备份 到 新的备份 脚本无法运行 那我可以理解为 我的老服务器mongodb太老现在太新吗

那我应该如何去看，我目前适用哪个版本的mongodb。之前所有的评论是在哪个版本下评论的呀，数据会有记录吗？

或者有其他的解决方法吗，感谢大佬！期待大佬的回复

### Reproduction

debian12

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
    Memory: 804.76 MB / 1.92 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm

{
    "ok": 0,
    "message": "Cannot GET /v2"
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by comeweb** [comment]
目前我使用的版本是
Using MongoDB:      7.0.12
Using Mongosh:      2.2.10

**Comment by Innei** [comment]
可以提供 migration 的表信息吗

**Comment by comeweb** [comment]
感谢您的回复！！！！不知道以下信息是否对您有帮助！！

这是mongodb的信息
![image](https://github.com/user-attachments/assets/9da3591d-c757-48a0-9b56-b2853c1e75f5)
![image](https://github.com/user-attachments/assets/b5eb85a8-bc75-4a60-a3be-6f99cdea8740)

这是后端的信息
![image](https://github.com/user-attachments/assets/71094d04-6fbc-4d1c-8968-b1e924f96bd9)

**Comment by Innei** [comment]
删除这个表，重启一下试试

**Comment by comeweb** [comment]
> 删除这个表，重启一下试试

感谢大佬的回复

我删了唉 db.migrations.drop()了 也显示成功true了

也重启了一下 但是后台还是显示有问题

![image](https://github.com/user-attachments/assets/f4127ef4-cd28-4dbc-99eb-f8c138efdc22)

后端报错日志：

![image](https://github.com/user-attachments/assets/ff06d2b0-41ce-4547-a490-1f60d0c5d8fc)

迁徙日志已经删了
![image](https://github.com/user-attachments/assets/59b5de24-2249-4900-8067-7f92fe0d9a0c)

**Comment by Innei** [comment]
很奇怪的问题，方便把 comments 表 dump 给我吗

**Comment by Innei** [comment]
你的表数据脏了。需要手动修改 identifycounters 里面的 notes 删掉了，只保留 Note 那条。然后再把 migrations 删掉，重启 app 执行一遍迁移

**Comment by comeweb** [comment]
> 你的表数据脏了。需要手动修改 identifycounters 里面的 notes 删掉了，只保留 Note 那条。然后再把 migrations 删掉，重启 app 执行一遍迁移

哇爱您大佬！！！！修复了！！！另外是identitycounters表，我刚开始有点没找到这个集合。

![image](https://github.com/user-attachments/assets/06d6f400-4b19-4261-8176-1a1b0ee50c93)
我想记录一下，如果有后者说不定可以跟我一样来解决，我在mongodb里面执行了：

db.identitycounters.deleteOne({ modelName: 'notes' })
删除notes只保留
db.identitycounters.find().pretty()
查看当前是不是只剩下note.
db.migrations.drop()
删除migrations
