### ISSUE TITLE
无法启用 OAuth 方式

### ISSUE THREAD

**Issue by ghost** [mx-space/core#2101]
### Describe the bug

如题
浏览器发送请求载荷为 
```json
{"providers":[{"type":"github","enabled":true}],"secrets":{"github":{"clientSecret":"REDACTED"}},"public":{"github":{"clientId":"REDACTED"}}
```
返回数据为
```json
{
    "providers": [
        {
            "type": "github",
            "enabled": false
        }
    ],
    "secrets": {
        "github": {
            "client_secret": "REDACTED"
        }
    },
    "public": {
        "github": {
            "client_id": "REDACTED"
        }
    }
}
```

### Reproduction

设置 OAuth 并启用

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum
    Memory: 930.86 MB / 1.69 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: 9.9.0 - ~/.local/share/pnpm/pnpm
API: https://blog.lar.moe/api/v2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Fixed
