### ISSUE TITLE
Docker部署依赖问题

### ISSUE THREAD

**Issue by YKMdB3p** [mx-space/core#2119]
### Describe the bug

v6.0.3之后的版本引入了sharp依赖，但使用Docker部署镜像无法正常安装sharp，图像相关的功能不能正常工作。

### Reproduction

Docker平台部署

### System Info

```Shell
Installing sharp...
added 11 packages, and audited 12 packages in 20s
3 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
 ERROR   [ImageService]  sharp install failed: Cannot find module 'sharp'
Require stack:
- /root/.mx-space/node_modules 
 ERROR  Cannot find module 'sharp'
Require stack:
- /root/.mx-space/node_modules
  Require stack:
  - /root/.mx-space/node_modules
  at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
  at Module._load (node:internal/modules/cjs/loader:1051:27)
  at Module.require (node:internal/modules/cjs/loader:1311:19)
  at require (node:internal/modules/helpers:179:18)
  at requireDepsWithInstall (entrypoints.js:2:645150)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
fixed 519ba0babe641a309501b621b1daef8e4efa970e

**Comment by TinsFox** [comment]
用 f8c45e4120f1109 的源码 build 出来的镜像会找不到 sharp
<img width="954" alt="image" src="https://github.com/user-attachments/assets/c9fcc28e-c2ef-46fc-8ac6-4a18389d7262">

**Comment by AprilNEA** [comment]
latest 依旧有这个问题
