### ISSUE TITLE
备份的时候没有将mongoDB的数据备份进来

### ISSUE THREAD

**Issue by liyown** [mx-space/core#2204]
### Describe the bug

备份的时候没有将mongoDB的数据备份进来
![image](https://github.com/user-attachments/assets/2039d964-96e3-4313-8bf3-72c240a20b62)
![image](https://github.com/user-attachments/assets/44b7a13f-801f-480c-bfab-d84c3838fb1f)

### Reproduction

看图

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
    Memory: 185.74 MB / 1.92 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm

https://me.liuyaowen.cn/api/v2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
![CleanShot 2024-10-30 at 9  29 32@2x](https://github.com/user-attachments/assets/bc187aac-1682-4dbe-a769-8665abf3f108)
是有哦

**Comment by liyown** [comment]
会这么小嘛，我看db文件夹70多MB 我都怕迁移了
