### ISSUE TITLE
 关于服务端撰写文章是否可以移植掘金的ByteMD

### ISSUE THREAD

**Issue by xkfe** [mx-space/core#2205]
### Clear and concise description of the problem

我看到 server 撰写文章没有预览模式，如果是在线写 markdown 文章会有点难受。感觉 https://bytemd.js.org 不错，是否可以考虑下集成？如果能加入主题和代码高亮就更好了！

### Suggested solution

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/69eecd1e-8c4e-4bd4-96cb-8e97e1730ee9">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xkfe** [comment]
我们的管理面板差距好像有点大😅
面板版本: 4.7.3
系统版本：7.1.9

<img width="978" alt="image" src="https://github.com/user-attachments/assets/d0d67b86-4746-484f-a65d-f1164e8bbe53">
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/5cf5cb73-bbdc-495b-a7c8-cda68342f81c">

**Comment by CKylinMC** [comment]
[vditor](https://b3log.org/vditor/demo/index.html)也不错

**Comment by Innei** [comment]
可以在本地写。然后复制过去

**Comment by Innei** [comment]
预览现在就有

https://github.com/user-attachments/assets/228999c4-001c-4efc-ad3c-af2dba8d4744
