### ISSUE TITLE
希望增加博文加密功能：支持博文加密发布，仅授权用户可查看内容

### ISSUE THREAD

**Issue by Cheng-pi** [mx-space/core#2206]
### Clear and concise description of the problem

写博文时，可能会包含一些比较私密的内容，比如只希望特定朋友看到的内容，或者只给团队内部的人看的资料。目前，项目内还没有提供这种保护内容隐私的功能。希望能够支持博文加密发布

### Suggested solution

写博文时，可能会包含一些比较私密的内容，比如只希望特定朋友看到的内容，或者只给团队内部的人看的资料。目前，项目内还没有提供这种保护内容隐私的功能。希望能够支持博文加密发布

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
只有日记支持。其他暂时不会考虑
