### ISSUE TITLE
更新最新版OAuth失效

### ISSUE THREAD

**Issue by jiuyue52** [mx-space/core#2247]
### Describe the bug

佬，后端点验证报错403，429，前端登录报redirect_uri；是需要等后续更新，还是需要重新设置些什么？
Callback URL填的是`https://mx.vlo.cc/api/v2/auth/callback/github`，更新前是没问题的

![image](https://github.com/user-attachments/assets/540d403c-6008-47fc-9095-6553d438e983)

### Reproduction

后端验证403

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 AMD EPYC 7402 24-Core Processor
    Memory: 5.94 GB / 7.75 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.13.2 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jiuyue52** [comment]
更新到Core 7.2.3依旧报403

**Comment by jiuyue52** [comment]
使用的远程redis/mongodb；redis：7.4.1，mongodb：7.0.15

**Comment by sorrow233** [comment]
我也是一样，之前可以用密码登陆前端，现在连前端都没法登陆了喵。你是怎么回退的

**Comment by jiuyue52** [comment]
> 我也是一样，之前可以用密码登陆前端，现在连前端都没法登陆了喵。你是怎么回退的

后端回退的话直接在docker-compose.yml改版本号比如latest>7.1.9，前端的话我没回退过

**Comment by Innei** [comment]
报错信息是什么

**Comment by jiuyue52** [comment]
> 报错信息是什么
![image](https://github.com/user-attachments/assets/be497790-8a2e-4020-85a6-d8761471e177)

![image](https://github.com/user-attachments/assets/a85f4bbd-0b71-476a-8d8a-0ad47362f4a4)

**Comment by jiuyue52** [comment]
这是需要在core的docker-compose中添加mx.vlo.cc么？还是在哪设置🤔

![image](https://github.com/user-attachments/assets/caeb7041-d1c1-447b-a422-b392a255977e)

**Comment by sorrow233** [comment]
> 报错信息是什么

复现步骤：在前端和后端点击验证和登陆时100%触发

后端：

频繁返回 HTTP 403 (Forbidden) 和 HTTP 429 (Too Many Requests) 错误
错误日志（后端）：

```
POST https://api.sorrow233.cn/api/v2/auth/sign-in/social?currentURL=https%3A%2F%2Fapi.sorrow233.cn%2Fproxy%2Fqaqdmin%23%2Fsetting%2Fauth%3Fvalidate%3D 403 (Forbidden)
POST https://api.sorrow233.cn/api/v2/auth/sign-in/social?currentURL=https%3A%2F%2Fapi.sorrow233.cn%2Fproxy%2Fqaqdmin%23%2Fsetting%2Fauth%3Fvalidate%3D 429 (Too Many Requests)
```

前端：

调用 GET https://api.sorrow233.cn/api/v2/auth/csrf 接口时，返回 HTTP 404 (Not Found) 错误。
调用 POST https://api.sorrow233.cn/api/v2/auth/signin/data 接口时，也返回了 HTTP 404 (Not Found) 错误。

错误日志（前端）：

```
GET https://api.sorrow233.cn/api/v2/auth/csrf 404 (Not Found)
POST https://api.sorrow233.cn/api/v2/auth/signin/data 404 (Not Found)
Uncaught (in promise) SyntaxError: Failed to execute 'json' on 'Response': Unexpected end of JSON input
```

**Comment by jiuyue52** [comment]
> 这是需要在core的docker-compose中添加mx.vlo.cc么？还是在哪设置🤔

还真是，在 ALLOWED_ORIGINS 添加上后端域名后，不报403了，但是又报redirect_uri了🤔，应用程序回调地址配的https

**Comment by sorrow233** [comment]
> 在 ALLOWED_ORIGINS 添加上后端域名后，不报403了

你是对的。确实是因为ALLOWED_ORIGINS的原因返回403。github中redirect_uri需要填http才行，但依旧不能正常鉴权，返回的错误是。GPT说是因为 //fn 这里有两个斜杠，你有什么头绪优化吗
```
19:31:06  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
19:31:10  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
19:31:17  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
19:31:22  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
19:31:34  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
```

**Comment by Innei** [comment]
> > 在 ALLOWED_ORIGINS 添加上后端域名后，不报403了
> 
> 你是对的。确实是因为ALLOWED_ORIGINS的原因返回403。github中redirect_uri需要填http才行，但依旧不能正常鉴权，返回的错误是。GPT说是因为 //fn 这里有两个斜杠，你有什么头绪优化吗
> 
> ```
> 19:31:06  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> 19:31:10  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> 19:31:17  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> 19:31:22  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> 19:31:34  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> ```

env 里面 api-url 不要带尾斜杠

**Comment by jiuyue52** [comment]
> env 里面 api-url 不要带尾斜杠

佬，现在报redirect_uri有什么办法没，nginx配置感觉没问题（因为老版本是可用的🥹）

**Comment by Innei** [comment]
> > env 里面 api-url 不要带尾斜杠
> 
> 佬，现在报redirect_uri有什么办法没，nginx配置感觉没问题（因为老版本是可用的🥹）

都填 http

**Comment by jiuyue52** [comment]
> 都填 http

google的正式版只能https, 让他一直停在测试版就行么

**Comment by sorrow233** [comment]
不是因为这个，因为你的网站也会报这个错（

**Comment by Innei** [comment]
> > 都填 http
> 
> google的正式版只能https, 让他一直停在测试版就行么

![CleanShot 2024-12-01 at 9  34 03@2x](https://github.com/user-attachments/assets/63963639-5be0-434f-a4ea-6071b6f68fb8)

**Comment by Innei** [comment]
> > > 在 ALLOWED_ORIGINS 添加上后端域名后，不报403了
> > 
> > 
> > 你是对的。确实是因为ALLOWED_ORIGINS的原因返回403。github中redirect_uri需要填http才行，但依旧不能正常鉴权，返回的错误是。GPT说是因为 //fn 这里有两个斜杠，你有什么头绪优化吗
> > ```
> > 19:31:06  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> > 19:31:10  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> > 19:31:17  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> > 19:31:22  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> > 19:31:34  WARN   [AllExceptionsFilter]  IP: ***.***.***.*** 错误信息：(404) Cannot POST /api/v2//fn/ps/update Path: /api/v2//fn/ps/update
> > ```
> 
> env 里面 api-url 不要带尾斜杠

这个应该是你用的上报程序的 api url 有尾随/

**Comment by jiuyue52** [comment]
> ![CleanShot 2024-12-01 at 9  34 03@2x](https://private-user-images.githubusercontent.com/41265413/391335474-63963639-5be0-434f-a4ea-6071b6f68fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjA0MjMsIm5iZiI6MTczMzA2MDEyMywicGF0aCI6Ii80MTI2NTQxMy8zOTEzMzU0NzQtNjM5NjM2MzktNWJlMC00MzRmLWE0ZWEtNjA3MWI2ZjY4ZmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDEzMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MDc5ZGI2OTkxNTljZTYwZTQ0NjkwOWUyYTUzNjUyMmQzNWYxMzk3ZjRiOTNhMTUxZDQxM2EzMjdjN2NlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f9jYsrD4aY3jf3UYHyzBw3omS3tUsWxdAgVZ8yhzw6k)



已获授权的 JavaScript 来源 和 已获授权的重定向 URI，这两个只要有http就只能这样，虽然能用来着0.0（ 


![image](https://github.com/user-attachments/assets/84652e87-9245-4f5e-a944-03e8c17581d5)
![image](https://github.com/user-attachments/assets/fccb30ad-316b-44de-b706-f5b3b372f4e2)

**Comment by sorrow233** [comment]
> 这个应该是你用的上报程序的 api url 有尾随/

更邪门了，后端Google和GitHub都成功了，前端依旧闪一下，返回200，甚至后端已经显示了新读者，但还是没登录上，很大概率vercel的问题吧？已老实
![](https://pic.k-on.live/file/1733068179355_image.png)
