### ISSUE TITLE
将Cloudflared注入镜像

### ISSUE THREAD

**Issue by sysfox** [mx-space/core#2251]
### Clear and concise description of the problem

twikoo有使用Huggingface Space部署的方案，通过cloudflared来进行流量代理
但我效仿该方案时遇到了一些困难，如Cloudflared并未如期启动
希望mix-space可以直接将Cloudflared整合入镜像，并通过环境变量的形式来传入Cloudflared的token

### Suggested solution

注入Cloudflared

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sysfox** [comment]
#2252 已实现

**Comment by Innei** [comment]
Thank you!
