### ISSUE TITLE
packages/complied 包名似乎拼写错误,或许应该是compiled才符合语义

### ISSUE THREAD

**Issue by wh5938316** [mx-space/core#2266]
### Additional context

感谢作者对于 better-auth 不支持cjs的解决方案，但是似乎包名存在语义错误，我在阅读的时候无法理解complied在这里的含义，或许compiled才是正确的

**Comment by Innei** [comment]
修复了！

**Comment by wh5938316** [comment]
> 修复了！

你好快！
