### ISSUE TITLE
Algolia 超出记录大小

### ISSUE THREAD

**Issue by bcw222** [mx-space/core#2271]
Algolia 免费计划的记录大小上限为10000字节，但稍微长一点的中文内容很容易就会超出这个限制导致无法推送索引。
按 Algolia 的官方文档好像可以通过分片之类的方式解决这个问题，然而目前 mx-space/core 好像还不支持。有什么解决方案吗？

**Comment by Do1e** [comment]
可以考虑[我的方法](https://www.do1e.cn/posts/code/algolia-search)， #2243 

或者使用目前代码中的截断方案，但是要将代码中的这里改成10000：

https://github.com/mx-space/core/blob/838b5b33a05724c776d6d19adc4784dc75679daa/apps/core/src/modules/search/search.service.ts#L370

@Innei 或许这里修改为环境变量会更好。

**Comment by Innei** [comment]
![CleanShot 2024-12-20 at 10  49 29@2x](https://github.com/user-attachments/assets/458e342f-24aa-4db0-94dd-94da5d3b0b9a)

**Comment by bcw222** [comment]
不懂就问，所以这个版本release了吗，或将在哪个版本release？我下载了 v7.2.4 的 release-linux.zip 部署但设定页里并没有这个选项。因为我在树莓派上部署而已有的其他部署方法在树莓派上不起作用，所以我依赖 release 的预构建包。如果能告诉我我何时能用上这个功能将不甚感激！

> ![CleanShot 2024-12-20 at 10  49 29@2x](https://private-user-images.githubusercontent.com/41265413/397774770-458e342f-24aa-4db0-94dd-94da5d3b0b9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDg1MjksIm5iZiI6MTczNDcwODIyOSwicGF0aCI6Ii80MTI2NTQxMy8zOTc3NzQ3NzAtNDU4ZTM0MmYtMjRhYS00ZGIwLTk0ZGQtOTRkYTVkM2IwYjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE1MjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OWFhZDM3MGZjMDVkMzFmMDE1ODAxMWE3ODc5NDBhNGQ3MTJjNzM1N2NlMWVkY2I3YjgwZGU3Y2ZjZjZkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KZQ_lMBRRuot9_wYAwNUBSERkfINM_TD5WmSD-Pu5x0)

**Comment by Do1e** [comment]
看起来是构建出错了

https://github.com/mx-space/core/actions/runs/12433533929/job/34715276529

ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref mtxb9yuf9p4jgj6umh8kl21rp::ujyaq79dcrh5wqedzp5qy5px0: "/app/assets": not found

**Comment by Innei** [comment]
我修复一下
