### ISSUE TITLE
能否将接口的返回类型补充完善

### ISSUE THREAD

**Issue by AndSpark** [mx-space/core#400]
看了一下swagger，基本没有返回类型。想用swagger-typescript-api自动生成接口请求方法，结果只有请求参数能用，返回的类型基本上是any或void

**Comment by Innei** [comment]
> 看了一下swagger，基本没有返回类型。想用swagger-typescript-api自动生成接口请求方法，结果只有请求参数能用，返回的类型基本上是any或void

有 SDK 啊，https://github.com/mx-space/api-client
