### ISSUE TITLE
netease 云函数无返回

### ISSUE THREAD

**Issue by ttimochan** [mx-space/core#585]
netease 函数在最新的Core没有返回内容
使用的内容是[https://github.com/mx-space/snippets/blob/main/kami/functions/netease.ts](https://github.com/mx-space/snippets/blob/main/kami/functions/netease.ts)
本地pnpm dev出现以下内容
![](https://user-images.githubusercontent.com/91021824/174991864-fec0e751-7ec6-4995-9bc5-b2f474c016f5.png)
api-doc尝试，无返回
![](https://user-images.githubusercontent.com/91021824/174991650-cc0c275a-26f1-4de6-9a29-1a61a988fab1.jpg)
song 函数响应正常
![](https://user-images.githubusercontent.com/91021824/174991706-1c29f2e6-c5b1-4c68-81ec-bd0b14d2c869.jpg)

Curl netease 函数无返回
![](https://user-images.githubusercontent.com/91021824/174992104-fc564406-9beb-4ef3-962e-b14503f0c230.jpg)
在我尝试重新编辑该云函数的时候，出现了此错误
![](https://user-images.githubusercontent.com/91021824/174992240-aba56083-d2a6-4157-becf-c75d127547f2.jpg)
![](https://user-images.githubusercontent.com/91021824/174992263-324aa7f4-48b4-44df-97b4-7a7bc6be0b3f.jpg)

复现使用的系统是ArchLinux
Redis版本为 7.0.2 
MongoDB版本为 5.0.9
Node版本 v16.15.1

**Comment by Innei** [comment]
给个复现链接

**Comment by ttimochan** [comment]
> 给个复现链接

[https://www.timochan.cn/apc/fn/kami/netease](https://www.timochan.cn/apc/fn/kami/netease)
