### ISSUE TITLE
修改评论排序方式

### ISSUE THREAD

**Issue by yuano0** [mx-space/core#914]
## 问题
请问如何修改评论的排序方式

## 详细描述
手机端的排序方式是，最新评论在前
![C80E9DAC-CE0A-4B3E-96CC-5BBAF3E6F4E3](https://user-images.githubusercontent.com/106160716/188767146-5d1ece67-217f-4c6f-aa21-067e40cbc745.png)

可是电脑端的排序方式是，最老的评论在前。
![6CFAD1A4-5DE1-42A7-A06B-88F209D976CB](https://user-images.githubusercontent.com/106160716/188767157-096b4cd8-5b76-402e-9a87-b5cec52f8a68.png)

我想让电脑端，最新的在前，请问可以怎么改嘛...

**Comment by miaoermua** [comment]
在较新的 mx 前后端博客 https://www.miaoer.xyz 中不能复现手机评论和电脑版顺序不一致的情况，请尝试更新到最新的 core 和 kami，如还存在该情况请提供你使用的浏览器版本。
