### ISSUE TITLE
未完全更新后，前台显示502 Bad Gateway

### ISSUE THREAD

**Issue by yuano0** [mx-space/core#915]
## 问题
昨天上后台好像显示有新的更新 ---- 面板版本: 3.24.2。
我在后台Output那边更新，但是半小时一直没反应，随后去mix space文档手动更新。
![https://img.yuano.cc/upload/cankao01.png](https://img.yuano.cc/upload/cankao01.png)
参考的是这篇，安装依赖的时候 pnpm i 也一直未动，执行了后面的构建、启动前端。
最后前台崩了，https://yuano.cc/。显示502 Bad Gateway
请问怎么可以解决恢复一下呀......感谢！！后端显示是完好的。

对了，想起来我是国内的机器，可能拉取拉不到，所以一直更新不动....

### 系统环境
Ubuntu/20.04 LTS amd64（64 位） 
国内百度云主机。

### 报错日志
11:11:44  WARN   [AllExceptionsFilter]  IP: 错误信息: (404) Cannot GET / Path: /
11:11:45  WARN   [AllExceptionsFilter]  IP:  错误信息: (404) Cannot GET / Path: /
11:23:23  WARN   [AllExceptionsFilter]  IP: 错误信息: (404) Cannot GET /api/v2/init?t=Path: /api/v2/init?t=
11:23:25  WARN   [UserService]  主人已登录, IP:
11:23:25  WARN   [UserService]  主人已登录, IP:
11:24:22  WARN   [AllExceptionsFilter]  IP:错误信息: (404) Cannot GET / Path: /
11:26:20  WARN   [AllExceptionsFilter]  IP:错误信息: (404) Cannot GET /api/v2/init?t=Path: /api/v2/init?t=
11:26:22  WARN   [UserService]  主人已登录, IP: 
11:26:22  WARN   [UserService]  主人已登录, IP: 
11:29:29  WARN   [AllExceptionsFilter]  IP: 错误信息: (404) Cannot GET /api/v2/init?t=Path: /api/v2/init?t=
11:29:30  WARN   [UserService]  主人已登录, IP: 
11:29:31  WARN   [UserService]  主人已登录, IP: 
11:29:38  WARN   [UserService]  主人已登录, IP: 
11:30:04  WARN   [AllExceptionsFilter]  IP: 错误信息: (404) Cannot GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f Path: /owa/auth/logon.aspx?url=

**Comment by wibus-wee** [comment]
给错日志了，给一下 kami 的日志

此外，pnpm i 跑不动的话尝试换源

**Comment by ttimochan** [comment]
> ## 问题
> 昨天上后台好像显示有新的更新 ---- 面板版本: 3.24.2。 我在后台Output那边更新，但是半小时一直没反应，随后去mix space文档手动更新。 ![https://img.yuano.cc/upload/cankao01.png](https://camo.githubusercontent.com/21ef6c06aa016045cfffbbc75d8c97369a1d7f0865cb59ec6767ea11fdcdc0fd/68747470733a2f2f696d672e7975616e6f2e63632f75706c6f61642f63616e6b616f30312e706e67) 参考的是这篇，安装依赖的时候 pnpm i 也一直未动，执行了后面的构建、启动前端。 最后前台崩了，[https://yuano.cc/。显示502](https://yuano.cc/%E3%80%82%E6%98%BE%E7%A4%BA502) Bad Gateway 请问怎么可以解决恢复一下呀......感谢！！后端显示是完好的。
> 
> 对了，想起来我是国内的机器，可能拉取拉不到，所以一直更新不动....
> 
> ### 系统环境
> Ubuntu/20.04 LTS amd64（64 位） 国内百度云主机。
> 
> ### 报错日志
> 11:11:44 WARN [AllExceptionsFilter] IP: 错误信息: (404) Cannot GET / Path: / 11:11:45 WARN [AllExceptionsFilter] IP: 错误信息: (404) Cannot GET / Path: / 11:23:23 WARN [AllExceptionsFilter] IP: 错误信息: (404) Cannot GET /api/v2/init?t=Path: /api/v2/init?t= 11:23:25 WARN [UserService] 主人已登录, IP: 11:23:25 WARN [UserService] 主人已登录, IP: 11:24:22 WARN [AllExceptionsFilter] IP:错误信息: (404) Cannot GET / Path: / 11:26:20 WARN [AllExceptionsFilter] IP:错误信息: (404) Cannot GET /api/v2/init?t=Path: /api/v2/init?t= 11:26:22 WARN [UserService] 主人已登录, IP: 11:26:22 WARN [UserService] 主人已登录, IP: 11:29:29 WARN [AllExceptionsFilter] IP: 错误信息: (404) Cannot GET /api/v2/init?t=Path: /api/v2/init?t= 11:29:30 WARN [UserService] 主人已登录, IP: 11:29:31 WARN [UserService] 主人已登录, IP: 11:29:38 WARN [UserService] 主人已登录, IP: 11:30:04 WARN [AllExceptionsFilter] IP: 错误信息: (404) Cannot GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f Path: /owa/auth/logon.aspx?url=

可以尝试更换源，例如：
```bash
pnpm config set registry http://mirrors.cloud.tencent.com/npm/
```

请注意，当前文件夹下的 .npmrc 的设置项为最高优先级，请注意这个文件

**Comment by yuano0** [comment]
> 给错日志了，给一下 kami 的日志
> 
> 此外，pnpm i 跑不动的话尝试换源

PM2        | 2022-11-16T12:15:06: PM2 log: App [mx-kami:0] online
PM2        | 2022-11-16T12:15:07: PM2 log: App [mx-kami:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-11-16T12:15:07: PM2 log: App [mx-kami:0] starting in -fork mode-
PM2        | 2022-11-16T12:15:07: PM2 log: App [mx-kami:0] online
PM2        | 2022-11-16T12:15:08: PM2 log: App [mx-kami:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-11-16T12:15:08: PM2 log: App [mx-kami:0] starting in -fork mode-
PM2        | 2022-11-16T12:15:08: PM2 log: App [mx-kami:0] online
PM2        | 2022-11-16T12:15:08: PM2 log: App [mx-kami:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-11-16T12:15:08: PM2 log: App [mx-kami:0] starting in -fork mode-
PM2        | 2022-11-16T12:15:08: PM2 log: App [mx-kami:0] online
PM2        | 2022-11-16T12:15:10: PM2 log: App [mx-kami:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-11-16T12:15:10: PM2 log: App [mx-kami:0] starting in -fork mode-
PM2        | 2022-11-16T12:15:10: PM2 log: App [mx-kami:0] online
PM2        | 2022-11-16T12:15:11: PM2 log: App [mx-kami:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-11-16T12:15:11: PM2 log: Script /usr/bin/bash had too many unstable restarts (16). Stopped. "errored"

/root/.pm2/logs/mx-kami-out-0.log last 15 lines:
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env
0|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
0|mx-kami  | info  - Loaded env from /root/mx-space/kami/.env

/root/.pm2/logs/mx-kami-error-0.log last 15 lines:
0|mx-kami  | Require stack:
0|mx-kami  | - /root/mx-space/kami/next.config.js
0|mx-kami  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
0|mx-kami  |     at Function.mod._resolveFilename (/root/mx-space/kami/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/require-hook.js:27:32)
0|mx-kami  |     at Function.mod._resolveFilename (/root/mx-space/kami/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/require-hook.js:27:32)
0|mx-kami  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
0|mx-kami  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
0|mx-kami  |     at require (node:internal/modules/cjs/helpers:102:18)
0|mx-kami  |     at Object.<anonymous> (/root/mx-space/kami/next.config.js:3:31)
0|mx-kami  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
0|mx-kami  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
0|mx-kami  |     at Module.load (node:internal/modules/cjs/loader:981:32) {
0|mx-kami  |   code: 'MODULE_NOT_FOUND',
0|mx-kami  |   requireStack: [ '/root/mx-space/kami/next.config.js' ]
0|mx-kami  | }

大佬是这个么。另外我刚刚执行pnpm build这个命令的时候，他报错了， ELIFECYCLE  Command failed with exit code 1.

**Comment by wibus-wee** [comment]
重新 pnpm i 再 build 吧，一次不行多几次

**Comment by yuano0** [comment]
> 重新 pnpm i 再 build 吧，一次不行多几次

我根据上面的
`pnpm config set registry http://mirrors.cloud.tencent.com/npm/`
换了一下源，但是pnpm i 还是一直警告报错不行，请问这如何解决呀.....
