### ISSUE TITLE
更换域名后出现问题

### ISSUE THREAD

**Issue by Rockney99** [mx-space/core#916]
### Describe the bug

![Y6UP%3IR1@29M )49R_H@{S](https://user-images.githubusercontent.com/42824224/195162524-7e88c2f2-bba9-4a40-a925-3288b5dbb679.png)
![C0U0N RGD}B87{SE8U8YW8G](https://user-images.githubusercontent.com/42824224/195162530-fbe157db-b4c6-4521-8ded-29a886e2ae7e.png)

### Reproduction

更换域名后出现问题

### System Info

```Shell
api接口地址配置不正确，或者后端服务处线异常
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ttimochan** [comment]
在我看来，你可能是想把 roxxx 换成 yoxxx，那么在 kami 目录下，你应该修改 .env 文件，重新 pnpm build && pm2 start，使其生效

**Comment by Rockney99** [comment]
> 在我看来，你可能是想把 roxxx 换成 yoxxx，那么在 kami 目录下，你应该修改 .env 文件，重新 pnpm build && pm2 start，使其生效

非常感谢 按照你所说的操作了一遍已经解决问题了

**Comment by Rockney99** [comment]
现在还有个问题就是以前发布的文章现在进入后会显示网络错误，点一下刷新就恢复了 每次打开都是那样
![2RD%6{TEW5I07 S%B O)GC4](https://user-images.githubusercontent.com/42824224/195250483-a0c30265-e6df-4729-95eb-11706f79c99d.png)

**Comment by ttimochan** [comment]
> 现在还有个问题就是以前发布的文章现在进入后会显示网络错误，点一下刷新就恢复了 每次打开都是那样
> ![2RD%6{TEW5I07 S%B O)GC4](https://user-images.githubusercontent.com/42824224/195250483-a0c30265-e6df-4729-95eb-11706f79c99d.png)
> 

请提供复现链接

**Comment by ttimochan** [comment]
请检查你的 CORS 设置，即后端的 .env 文件，我发现了跨域错误

**Comment by Rockney99** [comment]
修改后端.env文件重新构建后已恢复正常 感谢你的帮助
