### ISSUE TITLE
使用docker一键部署脚本部署后，mx-admin界面会出现黑条，并且再setup-api中无法设置

### ISSUE THREAD

**Issue by sakurasep** [mx-space/core#997]
### Describe the bug

![image](https://user-images.githubusercontent.com/70024132/222733598-da585405-b646-4a39-b1da-548f2d0ee95e.png)
![image](https://user-images.githubusercontent.com/70024132/222733650-8de6112d-cc24-4cb5-b9e1-e34e88175e2c.png)
后台界面上出现黑条，因为我是mx-space的老用户，之前老版本（一年前？）部署的时候不存在这个问题，因为之前的云服务器到期了又换了一个重新部署最新的版本，遇到了这个问题。不知道是不是自己操作出了问题。
![image](https://user-images.githubusercontent.com/70024132/222733771-f7b164a6-4bcb-4080-8abc-090652223b90.png)
使用docker一键部署脚本

### Reproduction

全新的服务器，先按照前置要求配置安装docker和nvm之后，使用一键部署脚本，初始化后台就会遇到这个问题，但是可以继续初始化个人信息

### System Info

```Shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 166.41 MB / 1.70 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sakurasep** [comment]
已解决，使用后台单独部署即可解决这个问题。
后台编译源码的时候也可以直接推送到github action，让它生成release。

**Comment by Rockney99** [comment]
> 已经解决，使用后台单一部分即可解决这个问题。 后台编写译码的时候也可以直接推送到github action，让它生成release。

我也遇到这问题了 能详细说一下怎么操作吗 不是很懂
